# Generated by Django 6.0.5 on 2026-06-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name': '欢迎页面'},
        ),
        migrations.AddField(
            model_name='welcome',
            name='link_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='跳转链接'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序权重'),
        ),
    ]
