# Generated by Django 6.0.5 on 2026-06-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_welcome_options_welcome_link_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='/banner/default.png', upload_to='banner')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('link_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='跳转链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '横幅轮播',
                'verbose_name_plural': '横幅轮播',
                'ordering': ['order'],
            },
        ),
    ]
