# Generated by Django 6.0.5 on 2026-06-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('order', models.TextField(verbose_name='内容')),
                ('img', models.ImageField(default='/notice/default.png', upload_to='notice')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '公共表',
                'verbose_name_plural': '公共表',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='跳转链接'),
        ),
    ]
