# Generated by Django 6.0.5 on 2026-06-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_notice_alter_banner_link_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['create_time'], 'verbose_name': '公共表', 'verbose_name_plural': '公共表'},
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name': '欢迎页面', 'verbose_name_plural': '欢迎页面'},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='order',
            new_name='content',
        ),
    ]
