# Generated by Django 6.0.5 on 2026-06-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_notice_options_alter_welcome_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='网格区域名')),
                ('desc', models.CharField(blank=True, max_length=32, null=True, verbose_name='网格简称')),
            ],
            options={
                'verbose_name_plural': '网格表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='居民姓名')),
                ('avatar', models.ImageField(default='default.png', upload_to='collection/%Y/%m/%d/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('score', models.ImageField(default=0, upload_to='', verbose_name='积分')),
            ],
            options={
                'verbose_name_plural': '网格员表',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='居民姓名')),
                ('name_pinyin', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名拼音')),
                ('avatar', models.ImageField(default='default.png', upload_to='collection/%Y/%m/%d/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.area', verbose_name='网格区域')),
            ],
            options={
                'verbose_name_plural': '采集表',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo', verbose_name='网格负责人'),
        ),
    ]
