# Generated by Django 6.0.5 on 2026-07-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_area_userinfo_collection_area_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='face_token',
            field=models.CharField(max_length=64, null=True, verbose_name='百度Token'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='avatar',
            field=models.ImageField(default='collection/default.png', upload_to='collection/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='score',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
