# Generated by Django 6.0.5 on 2026-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_activity_userinfo_mobile_joinrecord_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='joinrecord',
            constraint=models.UniqueConstraint(fields=('user', 'activity'), name='unique_user_activity'),
        ),
    ]
