# Generated by Django 6.0.5 on 2026-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_joinrecord_unique_user_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='userinfo/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
